#### debug is used when you want to see varibles values during running playbook

- name: Playbook for Learning Variables
  hosts: all
  vars:
    pkg: vsftpd
    myuser: testing
    mypass: testing
    webroot: /var/www/html
    myurl: https://www.w3schools.com/jsref/prop_option_index.asp
  
  tasks:
  - debug:
      msg: "{{ pkg }} and {{ mypass }} and {{ webroot }} and {{ myurl }}"  
  - name: Install package  
    yum:
      name: "{{ pkg }}"
      state: installed

  - name: Create User
    user:
        name: "{{ myuser }}"
        password: "{{ mypass | password_hash('sha512') }}"

  - name: Create folder
    file:
      path: "{{ webroot }}/vijay"
      state: directory


  - name: Download index file
    get_url:
      url: "{{ myurl }}"
      dest: /tmp
