- name: Database update with notify and handlers
  hosts: all
  gather_facts: true
  tasks:
  - debug: 
       msg: Check requirment for Database Installation
    failed_when: ansible_os_family == 'RedHat'
  
  - name: Copy database scrips
    copy:
      src: /root/notify-handlers/install.sh
      dest: /root
      mode: 755

  - name: run the scrips
    shell: /root/install.sh
    register: output
    notify: db-restart
    changed_when: '"updated successfully in output.stdout"'

  handlers:
  - name: restart db service
    service:
       name: sshd
       state: reloaded
    listen: db-restart 
