- name: Example of Block and Rescue
  hosts: all
  tasks:
    - block:
        - name: download the database upgrade script
          get_url:
            url: https://www.w3schools.com/html/html_editors.asp
            dest: /tmp/test.sh
            mode: 0755

        - name: now start database upgrade
          shell: /tmp/test.sh

        - debug:
            msg: Database is upgrading
    
      rescue:
        
        - debug:
            msg: "Database started roolback"
