- name: Example of list of hash loop
  hosts: all
  tasks:

  - name: Create Groups
    group:
      name: "{{ item }}"
      state: present
    with_items:
      - admin
      - hr
      - finance
      - manager

  - name: Add users in different group
    user:
      name: "{{ item.name }}"
      group: "{{ item.group }}"
      state: present
    with_items:
        - { name: 'user21', group: 'admin' }
        - { name: 'user22', group: 'hr ' }
        - { name: 'user23', group: 'finance' }
        - { name: 'user24', group: 'manager' }
