## Example of loop to perform multiple task easily

- hosts: all
  gather_facts: true
  tasks:

  - name: Add multiple users
    user:
      name: "{{ item }}"
      state: present
    with_items:
        - user1
        - user2
        - user3
        - user4

  - name: Copies files
    copy:
      src: "{{ item }}"
      dest: /tmp
    with_items:
         - /etc/fstab
         - /etc/passwd
         - /etc/motd
