## Example of loop to perform multiple task easily

- hosts: all
  gather_facts: true
  vars_files:
    - /root/loops/list-users.yml
  tasks:

  - name: Add multiple users
    user:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ myusers }}"
