- name: Exampe of Nested loop
  hosts: all
  vars:
    myusers:
      - user21
      - user22
      - user23
      - user24
    mygroups:
      - unix
      - db
      - admin

  tasks:

  - name: First add three groups
    group:
      name: "{{ item }}"
      state: present
    with_items:
      -  "{{ mygroups }}"

  - name: add users to all groups
    user:
      name: "{{ item[0] }}"
      group: "{{ item[1] }}"
      append: yes
      state: present
    with_nested:
      - "{{ myusers }}"
      - "{{ mygroups }}"
