- name: Exampe of Nested loop
  hosts: all
  tasks:

  - name: First add three groups
    group:
      name: "{{ item }}"
      state: present
    with_items:
       - unix
       - db
       - admin

  - name: add users to all groups
    user:
      name: "{{ item[0] }}"
      group: "{{ item[1] }}"
      append: yes
      state: present
    with_nested:
      - { 'user21', 'user22', 'user23', 'user24' }
      - { 'unix', 'db', 'admin' }
