- hosts: all

  tasks:
  - file:
      path: /tmp/data
      state: directory


  - copy:
      src: /etc/fstab
      dest: /tmp/


  - service:
      name: crond
      state: restarted


  - yum:
      name:
        - ftp
        - vsftpd
      state: installed
