- name: Deploying tasks on all servers
  hosts: all
  tasks:
    - name: Creating a Directory
      file:
          path: /tmp/data
          state: directory


    - name: Copying of files
      copy:
          src: /etc/fstab
          dest: /tmp/


    - name: Restarting a Service
      service:
          name: crond
          state: restarted


    - name: Installation of Packages 
      yum:
        name:
         - ftp
         - vsftpd
        state: installed
